spring.application.name=usuariosapi
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5435/bd-usuarios
spring.datasource.username=user-bdusuarios
spring.datasource.password=pass-bdusuarios
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secretkey=7ExcwMPBax3uPexenqyy+CnKGD5rm3EmkUajcxgPHcQ=
